/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/ConnectBankAccount`; params?: Router.UnknownInputParams; } | { pathname: `/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/inbox/inbox`; params?: Router.UnknownInputParams; } | { pathname: `/invest/invest`; params?: Router.UnknownInputParams; } | { pathname: `/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/payments/payments`; params?: Router.UnknownInputParams; } | { pathname: `/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `/save/savings`; params?: Router.UnknownInputParams; } | { pathname: `/services/payment`; params?: Router.UnknownInputParams; } | { pathname: `/signup/signup`; params?: Router.UnknownInputParams; } | { pathname: `/signup/verification`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ConnectBankAccount`; params?: Router.UnknownOutputParams; } | { pathname: `/home/home`; params?: Router.UnknownOutputParams; } | { pathname: `/inbox/inbox`; params?: Router.UnknownOutputParams; } | { pathname: `/invest/invest`; params?: Router.UnknownOutputParams; } | { pathname: `/login/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/payments/payments`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/save/savings`; params?: Router.UnknownOutputParams; } | { pathname: `/services/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/verification`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/ConnectBankAccount${`?${string}` | `#${string}` | ''}` | `/home/home${`?${string}` | `#${string}` | ''}` | `/inbox/inbox${`?${string}` | `#${string}` | ''}` | `/invest/invest${`?${string}` | `#${string}` | ''}` | `/login/login${`?${string}` | `#${string}` | ''}` | `/onboarding/onboarding${`?${string}` | `#${string}` | ''}` | `/payments/payments${`?${string}` | `#${string}` | ''}` | `/profile/profile${`?${string}` | `#${string}` | ''}` | `/save/savings${`?${string}` | `#${string}` | ''}` | `/services/payment${`?${string}` | `#${string}` | ''}` | `/signup/signup${`?${string}` | `#${string}` | ''}` | `/signup/verification${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/ConnectBankAccount`; params?: Router.UnknownInputParams; } | { pathname: `/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/inbox/inbox`; params?: Router.UnknownInputParams; } | { pathname: `/invest/invest`; params?: Router.UnknownInputParams; } | { pathname: `/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/payments/payments`; params?: Router.UnknownInputParams; } | { pathname: `/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `/save/savings`; params?: Router.UnknownInputParams; } | { pathname: `/services/payment`; params?: Router.UnknownInputParams; } | { pathname: `/signup/signup`; params?: Router.UnknownInputParams; } | { pathname: `/signup/verification`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
